version: "3"
services:
  database:
    image: mysql:latest
    environment:
      MYSQL_LOWER_CASE_TABLE_NAMES: 2
      MYSQL_DATABASE: test
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    volumes:
      - ${MYSQL_VOLUME_PATH}:/var/lib/mysql
    networks:
      - test_network
    ports:
      - 3306:3306
    restart: always

#  application:
#    build: .
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/userdb
#    depends_on:
#      - database
#    ports:
#      - 8080:8080
#    restart: always
#    networks:
#      - test_network

networks:
  test_network: